./../../00_src/primitive_cell/full_adder.sv
./../../00_src/primitive_cell/half_adder.sv
./../../00_src/primitive_cell/adder.sv
./../../00_src/primitive_cell/mux.sv
./../../00_src/primitive_cell/counter.sv
./../../00_src/primitive_cell/register.sv
./../../00_src/primitive_cell/comparators.sv
./../../00_src/primitive_cell/shifter_32bit.sv
./../../00_src/primitive_cell/shifter_64bit.sv
./../../00_src/primitive_cell/decoder.sv
./../../00_src/primitive_cell/encoder.sv
./../../00_src/primitive_cell/leading_zero_counter_32bit.sv
